name: On Push & PR
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Linting failed"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  # Broken: https://github.com/denosaurs/depsbot/issues/193
  # depsbot:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@master
  #     - name: Run depsbot
  #       uses: denosaurs/depsbot@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: sarisia/actions-status-discord@v1
  #       if: failure()
  #       with:
  #         title: "Depsbot failed"
  #         webhook: ${{ secrets.DISCORD_WEBHOOK }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - run: deno task test
      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Tests failed"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  status:
    needs: [lint, test, depsbot]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          title: "All good"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}